FROM python:3.10-slim as builder

WORKDIR /app

COPY pyproject.toml poetry.lock* ./

RUN pip install --no-cache-dir poetry

RUN poetry config virtualenvs.create false && poetry install --no-dev

COPY . .

EXPOSE 5000

CMD ["/bin/sh"]