---
- hosts: webservers
  become: true

  tasks:
    - name: Ensure Docker is installed
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Ensure Docker Compose is installed
      apt:
        name: docker-compose
        state: present

    - name: Create a volume for the Flask app artifact
      docker_volume:
        name: flask_app_artifact
        state: present

    - name: Pull the latest Flask app production image
      docker_image:
        name: flask-app-prod
        source: local

    - name: Pull the latest NGINX image
      docker_image:
        name: nginx-flask
        source: local

    - name: Start the Flask app and NGINX using Docker Compose
      docker_compose:
        project_src: docker-compose.yml
        state: present
        restarted: true