version: '3'

services:
  flask_app:
    image: flask-app-prod
    container_name: flask_app
    restart: always
    expose:
      - 5000
    volumes:
      - flask_app_artifact:/app
    environment:
      - FLASK_ENV=production
  
  nginx:
    image: nginx-flask
    container_name: nginx_server
    restart: always
    ports:
      - "80:80"
    depends_on:
      - flask_app

volumes:
  flask_app_artifact:
    external: true