version: '3'

services:
  api:
    build: .
    container_name: sentiment_api
    ports:
      - "5001:5001"
    environment:
      - DB_HOST=db
      - DB_NAME=sentiment_db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: sentiment_db
    environment:
      POSTGRES_DB: sentiment_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql